
def eirp_test():
    return {
        "Active AP Table": [
            {
                "AP Type": "505",
                "Active Clients": "0",
                "Flags": "ad",
                "Group": "D1_6F",
                "IP Address": "10.118.11.200",
                "Name": "IY_1F_AP01",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:52E/26.7/26.7/0",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:6/9.0/26.5/0",
                "Standby Clients": "0",
                "Uptime": "8d:1h:30m:12s"
            },
            {
                "AP Type": "505",
                "Active Clients": "1",
                "Flags": "ad",
                "Group": "D1_4F",
                "IP Address": "10.118.11.95",
                "Name": "D1_4F_AP05",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:100E/25.2/25.2/1",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:1/9.0/25.5/0",
                "Standby Clients": "0",
                "Uptime": "114d:0h:5m:54s"
            },
            {
                "AP Type": "505",
                "Active Clients": "2",
                "Flags": "ad",
                "Group": "D1_3F",
                "IP Address": "10.118.11.83",
                "Name": "D1_3F_AP33",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:36E/26.5/26.5/2",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:1/9.0/25.5/0",
                "Standby Clients": "0",
                "Uptime": "8d:1h:30m:11s"
            },
            {
                "AP Type": "505",
                "Active Clients": "4",
                "Flags": "ad",
                "Group": "D1_6F",
                "IP Address": "10.118.11.196",
                "Name": "D1_6F_AP26",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:64E/26.5/26.5/4",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:6/9.0/26.5/0",
                "Standby Clients": "0",
                "Uptime": "8d:1h:30m:15s"
            },
            {
                "AP Type": "515",
                "Active Clients": "0",
                "Flags": "Aad",
                "Group": "NTUST_MA_1F",
                "IP Address": "10.118.218.23",
                "Name": "MA_1F_AP101-2",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:161E/27.0/31.7/0",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:1/7.0/27.0/0",
                "Standby Clients": "0",
                "Uptime": "8d:1h:19m:1s"
            },
            {
                "AP Type": "505",
                "Active Clients": "0",
                "Flags": "ad",
                "Group": "D1_7F",
                "IP Address": "10.118.12.6",
                "Name": "D1_7F_AP06",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:100E/25.2/25.2/0",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:11/9.0/23.5/0",
                "Standby Clients": "0",
                "Uptime": "8d:1h:30m:16s"
            },
            {
                "AP Type": "505",
                "Active Clients": "2",
                "Flags": "ad",
                "Group": "D1_10F",
                "IP Address": "10.118.12.145",
                "Name": "D1_10F_AP25",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:100E/24.0/25.2/1",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:11/9.0/23.5/1",
                "Standby Clients": "0",
                "Uptime": "8d:1h:30m:28s"
            },
            {
                "AP Type": "505",
                "Active Clients": "0",
                "Flags": "ad",
                "Group": "D1_14F",
                "IP Address": "10.118.13.44",
                "Name": "D1_14F_AP04",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:56E/26.7/26.7/0",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:1/9.0/25.5/0",
                "Standby Clients": "0",
                "Uptime": "114d:0h:5m:53s"
            },
            {
                "AP Type": "503H",
                "Active Clients": "0",
                "Flags": "Aad",
                "Group": "NTUST_MA_5F",
                "IP Address": "10.118.218.140",
                "Name": "MA_5F_AP511",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:100E/27.0/27.7/0",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:11/9.0/24.7/0",
                "Standby Clients": "0",
                "Uptime": "8d:1h:15m:57s"
            },
            {
                "AP Type": "505",
                "Active Clients": "0",
                "Flags": "ad",
                "Group": "NTUST_MA_1F",
                "IP Address": "10.118.218.27",
                "Name": "MA_1F_AP125",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:116E/26.7/26.7/0",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:1/6.0/25.5/0",
                "Standby Clients": "0",
                "Uptime": "8d:1h:19m:0s"
            },
            {
                "AP Type": "505",
                "Active Clients": "1",
                "Flags": "ad",
                "Group": "D1_13F",
                "IP Address": "10.118.13.32",
                "Name": "D1_13F_AP32",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:52E/26.7/26.7/1",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:6/9.0/26.5/0",
                "Standby Clients": "0",
                "Uptime": "8d:1h:30m:10s"
            },
            {
                "AP Type": "505",
                "Active Clients": "4",
                "Flags": "ad",
                "Group": "D1_7F",
                "IP Address": "10.118.12.10",
                "Name": "D1_7F_AP10",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:116E/26.7/26.7/4",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:11/9.0/23.5/0",
                "Standby Clients": "0",
                "Uptime": "8d:1h:30m:15s"
            },
            {
                "AP Type": "505",
                "Active Clients": "1",
                "Flags": "ad",
                "Group": "D1_4F",
                "IP Address": "10.118.11.115",
                "Name": "D1_4F_AP25",
                "Outer IP": "N/A",
                "Radio 0 Band Ch/EIRP/MaxEIRP/Clients": "AP:5GHz-VHT:149E/26.7/26.7/1",
                "Radio 1 Band Ch/EIRP/MaxEIRP/Clients": "AP:2.4GHz-HT:11/9.0/23.5/0",
                "Standby Clients": "0",
                "Uptime": "114d:0h:5m:46s"
            }
        ],
        "_data": [
            "Flags: 1 = 802.1x authenticated AP; 2 = Using IKE version 2;",
            "A = Enet1 in active/standby mode;  B = Battery Boost On; C = Cellular;",
            "D = Disconn. Extra Calls On; E = Wired AP enabled; F = AP failed 802.1x authentication;",
            "H = Hotspot Enabled; K = 802.11K Enabled; L = Client Balancing Enabled; M = Mesh;",
            "N = 802.11b protection disabled; P = PPPOE; R = Remote AP;",
            "S = AP connected as standby; X = Maintenance Mode;",
            "a = Reduce ARP packets in the air; d = Drop Mcast/Bcast On; u = Custom-Cert RAP;",
            "i = Provisioned as Indoor; o = Provisioned as Outdoor;",
            "p = Restriction mode in POE-AF/AT;r = 802.11r Enabled; f = No Spectrum FFT support;",
            "Q = DFS CAC timer running; T = Flex Radio Mode is 2.4GHz+5GHz; t = Tri-Radio Mode Enabled;",
            "U = Flex Radio Mode is 5GHz; V = Flex Radio Mode is 2.4GHz; e = custom EST cert; W = Dual 5GHz Mode Enabled; 4 = Using WiFi Uplink",
            "Channel followed by * indicates channel selected due to unsupported configured channel.",
            "Spectrum followed by ^ indicates Local Spectrum Override in effect.",
            "Channel flags: +/- = 40 MHz, E = 80 MHz, S = 160 MHz, E+E = 80 + 80 MHz (i.e. 36E+149E)",
            "Cluster Role: U = UAC, A = AAC, SU = Standby UAC , SA = Standby AAC",
            "662"
        ],
        "_meta": [
            "Name",
            "Group",
            "IP Address",
            "AP Type",
            "Flags",
            "Uptime",
            "Outer IP",
            "Cluster Role",
            "Active Clients",
            "Standby Clients",
            "Radio 0 Band Ch/EIRP/MaxEIRP/Clients",
            "Radio 1 Band Ch/EIRP/MaxEIRP/Clients",
            "Radio 2 Band Ch/EIRP/MaxEIRP/Clients"
        ]
    }
